language: elixir
elixir:
  - 1.4
  - 1.8
otp_release:
  - 20.3
  - 21.0
matrix:
  exclude:
    - elixir: 1.4
      otp_release: 21.0
    - elixir: 1.8
      otp_release: 20.3
before_script:
  - mix local.hex --force
  - mix deps.get
script:
  - mix test
notifications:
  recipients:
    - williammelo@gmail.com
